### PR TITLE
KBHFF build automation

### LINKED ISSUE #4: Use Apache vhosts properly
I don't think the way we currently use vhosts is correct (or at least, standard): we echo include directives to the end of config files. We should instead put our config files in the sites-enabled directory and enable them.

### PR DESCRIPTION
**Pull request by FjolleJagt**
It is now working up to the janitor page where you configure the database. I've added a makefile to make building / running easier. Run `make build`, `make run` and then navigate to `http://kbhff.local/janitor/admin/setup`.

As part of getting it past the next step of the configuration, it seems a good time to split `mysql` and `redis` out into their own containers, fixing #5 .

This merge fixes #4 , to a large extent, though it would be good to check with Martin that the changes I made aren't going to break anything, and if possible incorporate them upstream.

### CODE REVIEW

**Comment by FjolleJagt** [comment]
Ah sorry, I forgot this branch wasn't merged when I pushed that latest commit - I only intend for the commits prior to me requesting a review being merged. (The last commit doesn't work because I haven't figured out how to wire up the mysql container to the apache one; I think the problem is that KBHFF expects mysql to be running on localhost.)

**Comment by FjolleJagt** [comment]
This is now done!

There are still improvements to be made, but it seems to be basically working. The `README.md` has updated instructions for how to build and run it. You need to run a bash script to clone & patch the git sources, then use docker-compose to build the images.

**Comment by cleborys** [comment]
- remove "badlist" file
- add remark in readme to stop mysql/apache before starting docker if already running website

**Review by cleborys — APPROVED** [review]

**Comment by FjolleJagt** [comment]
* Remove TODO file

**Pull request merged**
